/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chenchen_factory_ndk_HelloJni */

#ifndef _Included_com_chenchen_factory_ndk_HelloJni
#define _Included_com_chenchen_factory_ndk_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chenchen_factory_ndk_HelloJni
 * Method:    getPackageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chenchen_factory_ndk_HelloJni_getPackageName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
